/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src\themes\neutral\neutralTheme.ts
 * Command: astryx theme build src\themes\neutral\neutralTheme.ts --out src\themes\neutral\penn-state.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./penn-state.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
import type { IconRegistry } from '@astryxdesign/core/Icon';
export declare const neutralIconRegistry: IconRegistry;
export declare const pennStateTheme: DefinedTheme;
